name: CI/CD to GitHub Pages

on:
  push:
    branches:
      - main
      - setup-project
      - ui
      - backend
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Run frontend lint
        run: |
          cd client
          npm run lint
          

      - name: Type check frontend
        run: |
          cd client
          npm run type-check
      - name: Type check backend
        run: |
          cd backend
          npm run type-check

     # - name: Run tests
     #  run: npm test

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
